coastland/gsp-dba-maven-plugin

src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java

java1.6に対応するため、java1.7から導入されたStandardCharsetsクラスを使用しないように修正

java.nio.charset.StandardCharsetsを使用しないように修正

---

src/main/java/jp/co/tis/gsp/tools/db/beans/Column.java

今までDDLにシーケンス生成文が書き込まれる条件は
- ObjectBrowserの「デフォルト値」列に`AUTO_INCREMENT`と記載されている
- または単一主キー
のみでした。
これに
- 単一主キーの場合はデータ型が数値型である
という条件を追加しました。
エンティティ生成時の`@SequenceGenerator`アノテーション付与は別の情報から判断されていたので修正の必要がありませんでした。

シーケンス生成条件を厳しくして、文字型のカラムにシーケンスが張られたりしないようにした

---

recipe/spec-generatedEntity.md
src/main/resources/org/seasar/extension/jdbc/gen/internal/generator/tempaltes/java/gsp_entity.ftl

@TableGeneratorが使われることはないため以下から削除。
・エンティティに付与されるアノテーションの説明ドキュメントから説明を削除
・エンティティ生成のテンプレートから、@TableGenerator生成の分岐を削除

@TableGeneratorが使われることはないため、削除

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExecuteDdlMojo.java

- dropAll()の役割を下記のように変更。
- 指定スキーマがなければ作成する。
- 指定スキーマがあれば、空のスキーマに戻す。
- createUser()の役割を下記のように変更。
- 無条件で指定ユーザを削除。
- 指定ユーザを作成します。
- updateDefaultSchema()を新設しました。これはddlファイル実行前に呼び出されます。
- Postgresql、SQLServerはDDLを実行するまえに、デフォルトのスキーマやスキーマ探索パスを設定しておく必要があるため。
- 他のDBでは空実装。
- その他修正
- mysqlのdropAllの処理をDROP DATABASE文に変更。
- grantAllToAnotherSchema()のメソッド名をgrantAllToUser()に変更。

execute-ddl 処理のリファクタリング

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExecuteDdlMojo.java

- 変更点
- Before
各DialectでDBユーザに対して付与するスキーマ内オブジェクトの権限がテーブルだけになっているものが大きかった。統一されていなかった。
- After
各DialectでDBユーザに対するスキーマ内オブジェクトの権限付与対象オブジェクトをテーブルとビュー、シーケンスのみにした。

DBユーザに付与するスキーマ内オブジェクトの権限をテーブル、ビュー、シーケンスのみに変更。

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java

- 変更点
- Dialect内で何度も行われていたJDBCドライバクラスの登録処理をDialectFactory.getDialect()によるDialect生成時のDialect.setDriver()の中で行うようにしてみた。
- getJDBCConnection()の存在価値がなくなったので削除。元のDriverManager.getConnectionに戻した。
- コンストラクタを見直して不要な生成処理を隠ぺいしたかったがインターフェースが変わる可能性があるので一旦見送り。

Dialect内のJDBC登録処理を生成時のみに変更。getJDBCConnectionは不要なので削除。

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/AbstractDbaMojo.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/GenerateEntity.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/LoadDataMojo.java

- ゴール処理の前で、ユーザ名とスキーマ名をnormalize処理した値で上書きする。
- 以降の処理で、スキーマ名をnormalize処理している箇所を削除（＝変数schemaを参照するように）
- OracleDialectにおいて、normalizeメソッドを呼び出さずに直接StringUti.uppercaseメソッドを使って大文字化していたコードを削除。

全ゴールの処理前に、ユーザ名とスキーマ名をDialect毎のnormalize処理した値で上書きする。

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java

無駄なImport文があったみたいで変更点が多く見えますが、実質的な修正は[この一行](https://github.com/coastland/gsp-dba-maven-plugin/compare/develop...feature-10763?expand=1#diff-c4d4a5e68785e22b184da1d1abbdf779R54)です。

Oracle:Float型のデータをCSVからロードできるように修正。

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java

MySQL:ダンプ出力時のパラメータを追加。default-character-set=utf8, hex-blob

---

README.md
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/AbstractDbaMojo.java

以下の対応を行いました。
- MySQLの時にパラメータ：schemaが指定された時はエラーにするようにしました。
- MySQLの時はschemaがセットされないため、jdbcコネクションを取得し、そこからカタログ名（データベース名）を取得してそれをschema名にセットするように修正しました。

MySQLのスキーマ指定不可対応

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java

dropAll()からシーケンス削除処理を削除。

---

src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/DbTableMetaReaderWithView.java

ビューの場合に元テーブルの外部キーを取得する処理となっていなかった。
外部キーにビューの列が含まれていない場合にnullポで落ちるバグを修正。

外部キー情報の取得処理を修正。

---

src/main/resources/jp/co/tis/gsp/tools/db/template/postgresql/createIndex.ftl
src/main/resources/jp/co/tis/gsp/tools/db/template/postgresql/createTable.ftl

[postgresqlのPK定義方法変更](https://github.com/coastland/gsp-dba-maven-plugin/pull/75)のプルリクを受けて、PostgresqlのcreateIndex.ftlとcreateTable.ftlを修正。
- createTable.ftlよりプライマリキーの定義を削除。
- createIndex.ftlにプライマリキーの定義を追加。index情報のカラム情報よりPK列定義を行うように修正。

PostgreslqのPKの列定義順序の修正

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/Db2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/H2Dialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/OracleDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/PostgresqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExecuteDdlMojo.java

以下の修正を実施。
- ユーザ名≠スキーマ名の時に、adminUserでDDLを流す仕組みを削除。
- 上記に伴い、後付けで権限付与していたgrantAllToUser()を除去。
- Oracleのインポート時、ALL_OBJECTSテーブルより指定スキーマが所有者のオブジェクトを全部消す。
- OracleのdropAll時にcreateSchema()というメソッドでスキーマを作成していたが、createUser()と同じだったので、createUser()に寄せた。
- H2のエクスポート時に、Dropオプションを付与する。

Oracleのインポートエクスポートに関わる権限周りの処理を見直し

---

src/main/resources/org/seasar/extension/jdbc/gen/internal/generator/tempaltes/java/gsp_entity.ftl

下記の対応を行いました。
- GenerationTypeの設定
- Oracleの時は@SequenceGeneratorが出力される。
- Oracle以外の時は、ゴミとなっているgenerator属性は不要なので削除、GenerationTypeをIDENTITYに設定。
- 関連オブジェクトの結合カラム（外部キー）として定義されているフィールドに対して、「insertable=false, updateble=false」を付与する。

JPA対応:Oracle以外はGenerationTypeをIDENTITYに設定。

---

src/main/java/jp/co/tis/gsp/tools/dba/s2jdbc/gen/GspAttributeDescFactoryImpl.java
src/main/resources/org/seasar/extension/jdbc/gen/internal/generator/tempaltes/java/gsp_entity.ftl

- 下記のエンティティ生成処理の修正を実施。
- ジェネレータの名前をDBのシーケンス名と合わせ、エンティティ間でジェネレータ名が被らないように修正。  
[Eclipselink シーケンス仕様](https://wiki.eclipse.org/EclipseLink/Examples/JPA/PrimaryKey#Specifying_a_Sequence)
- @SequenceGeneratorのallocationSizeをDBのシーケンス増分値（現状GSPでは1）に一旦合わせる対応を入れる。

JPA(Eclipselink)仕様に合わせて、エンティティのシーケンス属性の値を修正。

---

pom.xml
src/it/simple-jpa-test/pom.xml
src/it/simple-jpa-test/src/test/resources/META-INF/persistence.xml

JPAのテスト(integration-test)で、persistence.xmlに定義する各ＤＢの接続情報などを、テストのjdbc_test.proptiesファイルから生成するように変更。

JPAテスト:persistence.xmlのプロパティファイル置換変数対応。

---

README.md
doc/db-status.md

今回のテスト実施の際に発覚したload-dataで扱えるデータ型や汎用モードにおける注意事項などを記載。
具体的な記載内容は以下の通り。
- OracleのLong型をサポート対象外とした。
- 原因は[ストリーム既にクローズ済みエラー問題](http://d.hatena.ne.jp/t_ita/20101108/1289210491)。
- H2
- OTHER型は利用不可。[Javaシリアライズオブジェクト用](http://www.h2database.com/html/datatypes.html#other_type)みたいなのでユニットテストから除外した。
- SqlServer
- BINARY型も汎用モードexport-schema/import-schemaのサポート対象外、ユニットテストから除外。

汎用モードのexport-schema/import-shcemaの制約事項とデータ型に関してドキュメントを整備

---

src/main/java/jp/co/tis/gsp/tools/dba/mojo/ExportSchemaMojo.java

- 変更内容
- Before
- エクスポート処理の際に使用する作業フォルダと実際の出力先が同じフォルダであった。
- After
- エクスポート処理の際に使用する作業フォルダを別途作成し、そこで生成したリソースを実際の出力先にjarとして出力する。
- 作業フォルダの作成場所は以下とする。
```
[実際の出力先]/../_exptmp
```

エクスポートリソース生成時のフォルダを一時フォルダで行うように修正。

---

doc/db-status.md
src/main/java/jp/co/tis/gsp/tools/dba/dialect/Dialect.java

- レビュー指摘対応
- 汎用ExportSchemaでサポートしていないデータ型が存在する場合のエラーメッセージの是正。
- 汎用Export/ImportSchemaにおけるデータ型制約事項を追記。

汎用ExportSchemaでサポートしていないデータ型が存在する場合のエラーメッセージの是正。

---

recipe/custom-DdlTemplate.md

- 変更点
- generate-ddlのカスタマイズ方法でサンプルとして存在していたシーケンス名の変更方法に、それに伴うgenerate-entityテンプレートの修正方法を追記。

シーケンス名変更に伴うgenerate-entityテンプレートの修正方法を追記

---

pom.xml
src/it/simple-jpa-test/pom.xml

* 以下の修正を適用したいため、JUnit4のバージョンを上げました。
https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md#security-fix-temporaryfolder-now-limits-access-to-temporary-folders-on-java-17-or-later
* 依存関係の修正のみです。
* 本PRはリリース不要。testスコープの依存関係の変更のみであり、生成される成果物に影響がないため。

JUnit4を現行バージョンにアップ

---

README.md

`MAVEN_OPTS` の環境変数が定義されていない場合、 `%MAVEN_OPTS%` の部分は空文字にならずそのまま埋め込まれてしまうため、コマンド例を削除。

doc: MAVEN_OPTS の設定方法からコマンド例を削除

---

pom.xml
src/main/java/jp/co/tis/gsp/tools/dba/dialect/MysqlDialect.java
src/main/java/jp/co/tis/gsp/tools/dba/mojo/ImportSchemaMojo.java
src/test/java/jp/co/tis/gsp/test/util/DBTestUtil.java

- [ファイルコピー処理の改善](https://github.com/coastland/gsp-dba-maven-plugin/commit/6f7b093159dd9fc80125bbfb2a03c0c83b17f1d3)
- Docker でのテストに直接は関係ないが、ファイルコピーの処理があまりにも遅く実行に時間がかかりすぎるので修正を入れました
- [MySQL用の修正](https://github.com/coastland/gsp-dba-maven-plugin/commit/5925805949e6fb860fc7a430cc5898966b258c11)
- MySQL の `--execute` オプションのパラメータをダブルクォーテーションで括ると、 Windows では問題ないが Linux 環境ではうまくパラメータが渡せないことがわかったため、ダブルクォーテーションを削除
- Windows 上でもテストを動かし、ダブルクォーテーションが無くてもテストが通ることを確認
- [Oracle用の修正](https://github.com/coastland/gsp-dba-maven-plugin/commit/d289c24ad282ad4e2e90b59d4b68f97aaed3cb11)
- Linux 上で動作させた場合、JDBC接続時のクライアント側のロケールが日本でなくなるため日付のフォーマットが `yyyy-MM-dd` ではない形になる
- これにより、日本ロケールでの日付フォーマットを前提とした部分がエラーになる
- テスト実行時のロケールをシステムプロパティで日本に固定することで、Linux環境上でもテストが通るように修正
- [SQL Server …

Dockerでテストできるようにする修正

---

README.md
en/README.md

JIRAチケット[JakartaEE10対応に伴い、JavaEE由来の文言の修正](https://nablarch.atlassian.net/jira/software/c/projects/NAB/issues/NAB-583?filter=allopenissues&jql=project%20%3D%20%22NAB%22%20AND%20statusCategory%20IN%20(%22To%20Do%22%2C%20%22In%20Progress%22)%20ORDER%20BY%20updated%20DESC)に関連し、
古いEclipseLink JPAのドキュメントへのリンクを置換した。
元のリンク（ https://wiki.eclipse.org/Introduction_to_EclipseLink_JPA_(ELUG) ）には`allocationSize`についての説明があったが、 Jakarta Persistence 3.1に対応するEclipseLink4.0のページ（ https://eclipse.dev/eclipselink/documentation/4.0/concepts/concepts.html#ENTITIES006 ）からは 説明が削除されていた。
元のリンクは`allocationSize`についての説明を補完する目的で添付されていたと見えるため、`allocationSize`についての説明が記載されているJakarta Persistence仕様のページを参照するように変更した。

古いEclipseLink JPAのページへのリンクを置換

---

src/main/java/jp/co/tis/gsp/tools/dba/dialect/SqlserverDialect.java

SQL Server利用時に、4,000文字を超えるVIEWを扱うと不完全なVIEW定義を取得してしまい、エンティティの生成（`generate-entity`）に失敗するという問題に対応。
動作確認として、以下を実施。
- 大量のダミーカラムを持つVIEWを作成して修正前は`generate-entity`に失敗し、修正後はエンティティの生成が可能になったことを確認
- ダミーカラムは `$ seq 1000 | perl -wp -e 's!(.+)!id as id$1_foo_bar_hoge, !' | perl -wp -e 's!\r?\n!!g'` で定義し、2,6000文字を超えるVIEW定義とした
- SQL Server 2017、2019、2021でテストを実行し、既存のテストが問題なく動作することを確認

SQL Server利用時に4,000文字を超えるVIEWを扱うと不完全な定義を取得してしまう問題に対応
